server:
  port: 8080
spring:
  profiles:
    group:
      default: domain, application, core, persistence, support-migration
      test: domain-test, application-test, core-test, persistence-test, support-migration-test
      prod: domain-prod, application-prod, core-prod, persistence-prod, support-migration-prod
  mvc:
    static-path-pattern: /test/**
  main:
    banner-mode: off
logging:
  level:
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF
