server:
  port: 8080
  deploy-version: 1.0.0
spring:
  profiles:
    group:
      default: domain, application, core, persistence, support
      test: domain-test, application-test, core-test, persistence-test, support-test
      prod: domain-prod, application-prod, core-prod, persistence-prod, support-prod
  mvc:
    static-path-pattern: /test/**
  main:
    banner-mode: off
  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/template?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: template
        password: template
        pool-name: 'read-write-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/template?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: template
        password: template
        pool-name: 'read-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/template?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: template
    password: template
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 63792
logging:
  level:
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF
