spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:33061/template?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: template
    password: template
    locations: classpath:db/migration
