spring:
  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/template_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: template
        password: template
        pool-name: 'read-write-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      hikari:
        jdbc-url: jdbc:mysql://localhost:33061/template_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: template
        password: template
        pool-name: 'read-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 63792
